[package]
name = "whiskers-palette"
version = "1.0.0"
edition = "2021"

[dependencies]
whiskers_palette_rs = { git = "https://github.com/Whiskers-Color-Scheme/whiskers-palette-rs" }
sniffer-rs = "1.1.1"
whiskers-launcher-core = "0.3.1"